################################################################################
# Title         : .travis.yml
# Date created  : 9 July 2020
# Author        : Erriez"
#
# This is a Continuous Integration script for Travis CI:
# - Build Arduino examples with PlatformIO by using the library sources.
# - Build Doxygen HTML and PDF and push this automatically to gh-pages. The
#   documentation is published at: https://<USER>.github.io/<REPOSITORY_NAME
#
#############################################################################

# Use Ubuntu 18.04 (Bionic Beaver)
dist: bionic

# PlatformIO requires deprecated Python 2.7
language: python
python: 2.7

# Cache platformIO directory
cache:
  directories:
    - "~/.platformio"

# Blacklist
branches:
  except:
    - gh-pages

# Install dependencies
addons:
  apt:
    packages:
      - doxygen
      - graphviz

# Install Python PlatformIO
install:
  - pip install -U platformio
  - platformio update

# Build script
script:
  - bash .auto-build.sh
